### ISSUE TITLE
Move backoff into the repository

### ISSUE THREAD

**Issue by josevalim** [fishcakez/db_connection#19]
I am considering if we should move backoff to the repository as db_connection_backoff.erl for two reasons:

1. Solve it in a way that's compatible with old and new Erlang versions alike
2. Remove one dependency

Thoughts?

**Comment by josevalim** [comment]
The dependency is probably alright, it is unlikely they will remove erlang:now() on Erlang 19.

**Comment by josevalim** [comment]
On the other hand it is so small that making it built-in makes a lot of sense.

**Comment by fishcakez** [comment]
We can remove the dependency sure. If we do this can we replace
`backoff_start` with `backoff_min`? So that the first (random) backoff is
random, not fixed.

**Comment by fishcakez** [comment]
Perhaps we could add a `rebar.config.script` so that backoff supports rebar2?

**Comment by josevalim** [comment]
It is up to you. :) moving in is easier because we then don't worry about
dep management.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
