### ISSUE TITLE
Don't log when owner/client exits if normal or shutdown

### ISSUE THREAD

**Issue by fishcakez** [fishcakez/db_connection#40]

**Comment by josevalim** [comment]
We only log If the someone is currently using the connection. So I think we
should always log, regardless of the reason. No?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by fishcakez** [comment]
Ah just for clients and not the owner, you are right.

**Comment by fishcakez** [comment]
This is for all pools btw, not ownership in particular.

**Comment by fishcakez** [comment]
@josevalim can you pick this up for and then change version in mix.exs 1.0.0-dev? We can't push a release as we are pointing at a git tag for sbroker and need to work on down stream repos first. In `DBConnection.Connection` we need to check the `:DOWN` reason and not log when reason is normal or shutdown. Ownership already does the correct thing.

**Comment by fishcakez** [comment]
@josevalim ok ill pickup :smile:

**Comment by fishcakez** [comment]
Closed in https://github.com/fishcakez/db_connection/commit/abfbc0b19ce0b10c189c118769740198a2b03cd4

**Comment by josevalim** [comment]
@fishcakez I was planning to do this today but glad you got to it first, thanks James! 
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
